# Generated by Django 2.2.1 on 2019-05-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20190522_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
